### ISSUE TITLE
[mc 1.15.2]dying while teleporting

### ISSUE THREAD

**Issue by joinmod** [henkelmax/advanced-mining-dimension#3] opened 2020-08-16 22:31 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

**Bug description**
when you trying return to overworld by some reason you start dying and loosing all XP but when you go back to mining dimension you stop dying and if you re join to world you XP restores

**Steps to reproduce the issue**
1. go to mining dimension
2. mine there
3. try go back to overworld

**Expected behavior**
successful return to overworld with LVL and not sufficating

**Log files**
[here logs](https://gist.github.com/joinmod/bef66b82bd8ad7677331b85f9aabae79).

**Versions**
- Minecraft version 1.15.2
- Forge version 31.2.30
- Mod version 1.0.4

**Other mods**
using mod pack HR: New Beginnings all mods updated manually

**Screenshots (Optional)**
[i have video shows how this is happening](https://youtu.be/7TWNsEZ59OQ)
UPD1:![death screen](https://user-images.githubusercontent.com/23500905/90345771-358f7b80-e02c-11ea-8fc6-31a96b9c4e0d.png)

**Comment by henkelmax** [comment] 2020-08-17 08:36
Unfortunately I am not able to reproduce this issue. This is most likely caused by another mod.
Does this issue occur without any other mods? If not, please narrow down the mod that causes this.
I can't see the death message in your logs. Are you sure these are the correct logs?

**Comment by joinmod** [comment] 2020-08-17 11:15
i think i found problem its caused by [performant](https://www.curseforge.com/minecraft/mc-mods/performant) 
mixinbootstrap 1.0.3 (lib for performant), performant 3.10m,

i loaded a test world and found out what only some coordinations will kill you and portal from mining dimension will be in overworld.

here another [video](https://youtu.be/Z_6X3OjAATE)

world seed: -6476272575931298853 (superflat)
mining portal coordination: -103, 4, -244

**Comment by henkelmax** [comment] 2020-08-17 16:13
Can you send me the log files of this incident?

**Comment by joinmod** [comment] 2020-08-17 17:00
ok so i created a new profile with performant and adv mining dimension for fast loading (new one not modpack) so first time with performant mining dimension getting fatal error but if turn OFF performant and then got to dimension and when ON fatal error does not appear until you create a new profile with 1.15.2 forge and install these mods
[LOG](https://gist.github.com/joinmod/ed84a209b6c9e7f435c78dc78d386359)

**Comment by henkelmax** [comment] 2020-08-17 20:55
It seems that this is a performant issue. Can you please report this bug on their tracker aswell?

**Comment by joinmod** [comment] 2020-08-17 22:11
ok.

i reported on their tracker

**Comment by henkelmax** [comment] 2020-08-18 08:07
Thanks!

**Comment by henkelmax** [comment] 2020-08-28 16:11
I am gonna close this issue, if there is any problem just let me know.

**Closed by henkelmax** 2020-08-28 16:11 UTC
Labels: bug

**Comment by ClaudiusMinimus** [comment] 2020-09-06 15:15
For any reading this before performant is fixed: I found sort of a workaround to keep from dying. If you start taking damage, then immediately use the portal again to teleport to/from the mining dimension. There is a good chance you will stop taking damage.

**Comment by ClaudiusMinimus** [comment] 2020-09-06 20:25
From my testing, this seems to only be a server related issue. When I disabled performant on my test server and then the production server the issue resolved.
