### ISSUE TITLE
Thermal Foundation Ores Aren't Spawning

### ISSUE THREAD

**Issue by Stormchaser465** [henkelmax/advanced-mining-dimension#37] opened 2021-02-24 04:27 UTC
As the title states, Thermal's ores don't generate in the mining dimension. The Create mod's ores are generating just fine, though. There are no log reports, as this isn't a bug that would create one. If there's files that I need to send to give a better picture, please let me know!

**Versions**
- Minecraft version 1.16.4
- Forge version 35.1.4
- Mod version 1.0.3

**Other mods**
Thermal Foundation (1.1.6)
Thermal Expansion (1.1.6)
Create (v0.3)
(& Associated libraries)

**Comment by henkelmax** [comment] 2021-02-24 08:03
Duplicate of #9

**Closed by henkelmax** 2021-02-24 08:03 UTC
Labels: bug
