### ISSUE TITLE
Take suffocation damage when entering the mining dimension

### ISSUE THREAD

**Issue by itsfriday19** [henkelmax/advanced-mining-dimension#13] opened 2020-09-29 18:32 UTC
I take continuous damage when I enter the mining dimension. I let it kill me and the death message said I was suffocating in a wall, which I wasn't. I have two portals, with the first I only take damage while I'm still standing on top of it, it stops when I move off. The second portal just keeps going until it kills me.

Edit: somehow it just flipped and now I'm taking suffocation damage in the overworld and not the mining dimension.

**Comment by henkelmax** [comment] 2020-09-29 18:48
Duplicate of #7

**Comment by henkelmax** [comment] 2020-09-29 18:48
Next time please use the provided issue templates.

**Closed** 2020-09-29 19:14 UTC
Labels: invalid
