### ISSUE TITLE
Player dies in wall when teleporting to mining dimension

### ISSUE THREAD

**Issue by ClaudiusMinimus** [henkelmax/advanced-mining-dimension#7] opened 2020-09-06 05:37 UTC
**Bug description**
I have a player on my server with a [pack I just released](https://www.curseforge.com/minecraft/modpacks/survival-in-chaos/files/3050626) that when he teleports to the mining dimension he dies. The message is he suffocated in a wall, but he was not in a wall.

**Steps to reproduce the issue**
1. The player teleports to the mining dimension
2. The player starts taking damage as soon as they arrive, though no apparent reason why
3. The player dies
4. The message states player suffocated in a wall
5. _This seems to be a server and not a singleplayer issue_

**Expected behavior**
Teleport safely to and from the mining dimension.

**Log files**

- [debug.log](https://github.com/henkelmax/advanced-mining-dimension/files/5179015/debug.log)
- [latest.log](https://github.com/henkelmax/advanced-mining-dimension/files/5179016/latest.log)

**Versions**
- Minecraft version 1.15.2
- Forge version 31.2.36
- Mod version mining_dimension-1.15.2-1.0.4

**Other mods**
If I had to guess I think it might be Ma Esentials causing the issue. I will test further but thought you might want to know about this.
[Link to mod list](https://www.curseforge.com/minecraft/modpacks/survival-in-chaos/files/3050626)

**Screenshots (Optional)**
The player that died. I was in the mining dimension and witnessed this.
![2020-09-05_21 01 06](https://user-images.githubusercontent.com/17887664/92317428-b1426f80-efbd-11ea-857f-83357e1f49b2.png)
This was me teleporting home using /home from the mining dimension.
![2020-09-05_21 09 29](https://user-images.githubusercontent.com/17887664/92317430-b1db0600-efbd-11ea-82ec-561bd6807c76.png)
![2020-09-05_21 10 40](https://user-images.githubusercontent.com/17887664/92317431-b1db0600-efbd-11ea-86bc-b1205c325575.png)

**Comment by henkelmax** [comment] 2020-09-06 06:42
Duplicate of #3

**Closed by henkelmax** 2020-09-06 06:42 UTC
Labels: bug
